export const UPDATE_PARTIE = 'UPDATE_PARTIE';
export const CHARGER_PARTIE = 'CHARGER_PARTIE';
export const UPDATE_LISTE_JOUEURS = 'UPDATE_LISTE_JOUEURS';
export const UPDATE_UTILISATEUR = 'UPDATE_UTILISATEUR';
export const MESSAGE_RECU = 'MESSAGE_RECU';
export const MESSAGE_ENVOYE = 'MESSAGE_ENVOYE';
