export const UPDATE_NOM_JOUEUR = 'UPDATE_NOM_JOUEUR';
export const UPDATE_PARTIE = 'UPDATE_PARTIE';
export const CHARGER_PARTIE = 'CHARGER_PARTIE';
export const UPDATE_LISTE_JOUEURS = 'UPDATE_LISTE_JOUEURS';
export const UPDATE_UTILISATEUR = 'UPDATE_UTILISATEUR';
